import type { Metadata } from "next";
import "./globals.css";
import SmoothScrollProvider from "./SmoothScroll";

export const metadata: Metadata = {
  title: "StockTech Investment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SmoothScrollProvider>
          {children}
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
